{% set name = "ds_store" %}
{% set version = "1.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ds_store-{{ version }}.tar.gz
  sha256: c27d413caf13c19acb85d75da4752673f1f38267f9eb6ba81b3b5aa99c2d207c

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 1
  entry_points:
    - ds_store = ds_store.__main__:main

requirements:
  host:
    - pip
    - pytest
    - python
  run:
    - mac_alias >=2.0.1
    - python

test:
  imports:
    - ds_store
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://alastairs-place.net/projects/ds_store
  doc_url: https://ds-store.readthedocs.io/en/latest/
  summary: Manipulate Finder .DS_Store files from Python
  license: MIT
  # Awaiting upstream push to PyPI for LICENSE to end up in SDist
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - thewchan
