{% set name = "ds_store" %}
{% set version = "1.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c27d413caf13c19acb85d75da4752673f1f38267f9eb6ba81b3b5aa99c2d207c

build:
  number: 3
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - ds_store = ds_store.__main__:main

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - mac_alias >=2.0.1

test:
  imports:
    - ds_store
  requires:
    - pip
    - pytest
    - pytest-cov
    - tox
    - python {{ python_min }}
  source_files:
    - tests
  commands:
    - pip check
    - tox -e py

about:
  home: https://github.com/dmgbuild/ds_store
  doc_url: https://ds-store.readthedocs.io/en/latest/
  summary: Manipulate Finder .DS_Store files from Python
  license: MIT
  license_family: MIT
  # Awaiting upstream push to PyPI for LICENSE to end up in SDist
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - thewchan
